assembler: assembler.c assembler.h utils.c utils.h
	gcc -Wall -ansi -pedantic -c assembler.c utils.c -o assembler

file_utils: file_utils.c file_utils.h constant.h
	gcc -Wall -ansi -pedantic -c file_utils.c -o file_utils